### ISSUE TITLE
Canonicalization of Stream Name (ie, allow uppercase, numeric, invalid string names)

### ISSUE THREAD

**Issue by AlexanderMann** [datamill-co/target-postgres#102]
# Motivation

Stream names are not required per the [Singer Spec](https://github.com/singer-io/getting-started/blob/master/docs/SPEC.md) to conform to anything _other_ than to be `"string"s`...

Unfortunately for targets, this means that support for various taps requires supporting many varying formats etc.

Hacks and workarounds exist for this, but if a `tap` has a stream name which is upper case, often the user _cannot_ edit/update this without forking the repo etc.

***For those interested, please vote 👍 on this description for interest in this feature.***

## What we currently do

Presently, _any_ string is allowed for _any_ subtable. This means that if we detect a "nested table" in the data, we will create a "sub-table" where we canonicalize the "path" to that particular field.

ie, if we have a stream `foobar` which has an array field called `B@z`, that means the _path_ to the array field is `("foobar", "B@z")`. This path will be canonicalized as `foobar__b_z`.

[The notable exception for this, is that _stream names_ themselves, ie the "root" table name, _must_ be strings which are](https://github.com/datamill-co/target-postgres/pull/60/files#diff-52720fbc0113bc218f3f4719ab96bbc9R57):
- lowercased
- start with a letter
- contain _only_ alphanumeric characters _and_ `_` underscores

## Why we do what we currently do

This logic was introduced in #60. This PR sought to allow for sub tables to be _reasonable_ names derived from the data/field names provided.

At the time, this was because it was viewed that the _data_ which comes out of a `tap` is well out of the user's control, but that often the `stream` names are already of this format (ie, many API based taps stream's are lowercase etc.).

An attempt was made to make it such that stream names could be of any string format. However it was more work to do that at the time.

## Proposals

Table name mappings are currently stored on the "root" table in a db. ie, the `stream` name table. These mappings take a `path` to a `canonicalized name`.

ie, `(a, b, c, d)` -> `a__b__c__d` etc.

### Dedicated Metadata Table

We could move this mapping out of the JSON blob stored in the table's comment and into a dedicated table. Something akin to `_datamill_table_metadata`.

### Load Table Mappings

Each table's metadata could store the `path`. When `target_postgres` starts, it can list all tables present in the remote, iterate through them and fetch the `raw_name` thus building up a cache in memory of our `path` to `canonicalized name`.

This could even be done via sql with something like:

```sql
SELECT CAST(obj_description(oid) AS json)->'path'
FROM pg_class
WHERE relkind = 'r'
```

## Suggested Musical Pairing

https://www.youtube.com/watch?v=crjugtkXZN4

**Comment by AlexanderMann** [comment]
# Test Cases

Below are some things I think we should be concerned about with _whatever_ solution we choose. @awm33 if you could weigh in with your gut reaction to how you think each situation should behave:

## Non-Standard Stream Name

Stream comes in with a name like `x`, produces a root table with the name `y`?:

- `` : Empty string -> ???
- `streaM` : Contains capital letters -> ???
- `Stream` : Starts with capital letters -> ???
- `xxxx...xxx` : Extremely _long_ field (longer than the max identifier length) -> ???
- `@#%^&*((` : Non alphanumeric, underscor, dollar sign -> ???

## Non-Standard Stream Name, Nested Data

Stream comes in with a name like `x` and nested data, produces a child tables with names like `y__`?:

## Colliding Stream Name

Stream named `x` comes, another stream named `X` comes. These produce ???

ie, do we get _two_ distinct root tables, or do we let them populate the same remote table? If we make them distinct, what are they named?

## Colliding Stream Name, Nested Data

Stream named `x` comes with nested fields `a` and `c`, another stream named `X` comes with nested fields `b` and `d`. These produce ???

# Proposed Results

- Non-Standard Stream Name
  - Follow conventions set by nested fields/child tables:
    - Empty -> `_`
    - Capitals get lowercased
    - Long identifiers get truncated
    - Non alphanumeric, underscore, dollar sign -> `_`
  - Nested fields/data
    - Whatever the root table's name _ends up_ being, we use that as the prefix with `__` separating
      - **_NOTE_**: for long identifiers, this can potentially result in incredibly ugly/unusable table names etc.
- Colliding Stream Name
  - follow the conventions by other identifiers and append an integer till we get a unique value
    - NOTE: This will make nested fields etc. potentially _very_ confusing
  - Nested fields/data
    - same solution as above with the root table name being what we prefix with

# Proposed Solution

After having had time to think about this, I don't _think_ we have the information stored in a format presently which makes modifying this particularly convenient. ie, we're not storing the `path` to tables in the `metadata` already.

I think the simplest solution for us, is probably to go with the `Load Table Mappings` option from above. However, this _will_ required a schema bump, and migration etc.

The advantage to this approach is that adding and managing `table mappings` becomes _really_ straightforward. The disadvantage (potentially) is around managing the mappings when there are a _lot_ of resultant tables in a single Postgres schema.

That all being said, I think a spike to investigate this is worth it

# Proposed Hack

Sooooooooo...a route we could go here is to provide a config option for `dangerous__canonicalize_stream_name`. This would just disable the validation on the stream name, and then canonicalize it etc. I'm not sure how much work will be necessary for this, nor am I sure whether this can be even remotely forward compatible...

**Comment by AlexanderMann** [comment]
An issue that's popping up with this change is how we're currently handling table versioning stuffs. That logic has been shaky/known to be a bit bug ridden for a while due to it relying upon postfixes and whatnot. I think that if we're going to invest _more_ time into this procedure, we'll also need to invest time into shoring that logic up and making it a bit more airtight.

_This_ more than the other schema changes, could present a problem to existing schemas. If an activate version command has not yet come in, and then we decide to run this migration etc., we could easily break things etc.

**Comment by AlexanderMann** [comment]
Also, utilizing casting to json will not work with _native_ 8.4.22. _Redshift_ however has a bunch of json support baked into it...going to look into what all we _can_ and _cannot_ do across versions. Additionally, we may have to install some extensions etc. into our 8.4.22 tests.

**Comment by AlexanderMann** [comment]
Redshift supports the common [PSQL function JSON_EXTRACT_PATH_TEXT](https://docs.aws.amazon.com/redshift/latest/dg/JSON_EXTRACT_PATH_TEXT.html).

This is not available in 8.4.22...but...the _simplest_ thing to do _might_ be to make a function in 8.4.22 which is _called_ that, but really just takes text, a field, and returns a string array. That way it'd _behave_ like the actual call and response we expect, without us having to ditch the useful testing of 8.4.22 in lieu of more costly/time-consuming Redshift calls etc.

**Comment by AlexanderMann** [comment]
@gpetepg I think you were the one originally pushing for this functionality. The PR #131 _should_ address this. If you have any interest in looking that over for the functionality you're after, that'd be 👍

**Comment by gpetepg** [comment]
@AlexanderMann awesome! I am currently using a fork of the PR but will test this out asap and ping you in the slack channel. Haven't had as much time to use Singer as my project got shelved.
