### ISSUE TITLE
Collaboration and contributions

### ISSUE THREAD

**Issue by gpetepg** [datamill-co/target-postgres#103]
How should members of the community help contribute and collaborate with the team at Data Mill?

From my experience I recommend joining singer-io.slack.com and asking questions in the general chat and on each tap/target's specific channel.

Start a conversation with the owners of the repo. Here specifically @awm33 @AlexanderMann then:

File new issue -> Fork -> PR -> Approval -> Merge.

**Comment by AlexanderMann** [comment]
Yup, that all looks about right! @gpetepg do you want to fork and add in the necessary docs into the readme/etc.? If not @awm33 or myself will get around to it prolly before next week.

**Comment by gpetepg** [comment]
> Yup, that all looks about right! @gpetepg do you want to fork and add in the necessary docs into the readme/etc.? If not @awm33 or myself will get around to it prolly before next week.

I'll fork and make a PR before the end of the week. I'll take a look at the other taps and targets too and see what I can add so I can get more involved slowly.

**Comment by awm33** [comment]
I wouldn't make Slack an official/required part of the process, but recommend asking in the Singer Slack, and in particular the #target-postgres channel.

I like "File new issue -> Fork -> PR -> Approval -> Merge"

Users can file an issue without submitting a PR. I consider that contributing, they just can't expect it will be addressed.

**Comment by gpetepg** [comment]
Makes sense, I'll note both of those in the README. Working on it now.

**Comment by awm33** [comment]
Closed by https://github.com/datamill-co/target-postgres/pull/105
