### ISSUE TITLE
ValidationError: " '..' is not of type .. "

### ISSUE THREAD

**Issue by DylanDriessen** [datamill-co/target-postgres#114]
I bumped on following error using the tap-closeio on target-postgres.

`target_postgres.singer_stream.SingerStreamError: ('Invalid records detected above threshold: 0. See `.args` for details.', [(<ValidationError: "'2019-04-15T14:38:04.000000Z' is not of type 'object'">

It says that date: "2019-04-15T14: 38: 04.000000Z" behaves as an object type, while it should be a string with date-time format right?

I have added a file that contains the complete error, as well a file that shows my schema.

[postgres_error.txt](https://github.com/datamill-co/target-postgres/files/3108365/postgres_error.txt)

[catalog_activities.zip](https://github.com/datamill-co/target-postgres/files/3108378/catalog_activities.zip)

**Comment by AlexanderMann** [comment]
@DylanDriessen ahha! This one is actually pretty straightforward:

```json
    "date": {
      "inclusion": "automatic",
      "anyOf": [
        {
          "type": [
            "string"
          ],
          "format": "date-time"
        },
        {
          "type": [
            "string"
          ]
        }
      ]
    },
```

Your problem types are of `anyOf` type. _Currently_ `target-postgres` doesn't support this...

> JSON Schema combinations such as anyOf and allOf are not supported.

We've talked before about trying to support it in one mechanism or another, but right now it's not gonna go well 😢. We _could_ make the error message better though if you think that'd be helpful.

**Comment by DylanDriessen** [comment]
@AlexanderMann I've tried fixing this already before this post, seems like my current code didn't save to the one I've uploaded. I changed this with:
` "date": {
                  "inclusion": "automatic",
                  "format": "date-time",
                  "type": [
                    "string"
                  ]
                }`

But this resolves in the same error..

**Comment by AlexanderMann** [comment]
@DylanDriessen can you upload the new schema and error logs for the updated?

**Comment by DylanDriessen** [comment]
Here is the new specific schema with his error log which is the exactly the same as before
[postgres_error.txt](https://github.com/datamill-co/target-postgres/files/3112525/postgres_error.txt)
[catalog_activities.zip](https://github.com/datamill-co/target-postgres/files/3112519/catalog_activities.zip)

**Comment by AlexanderMann** [comment]
@DylanDriessen I threw together a simple set of tests in here: https://github.com/datamill-co/target-postgres/pull/115

If you look at the commit history, I have the first commit as a `fail` with your original `anyOf` type. After I change _just that_ everything seems to work correctly.

I'm wondering if _maybe_ some of your configs are pointing at the wrong place?

**Comment by DylanDriessen** [comment]
I see, after changing it to your schema it still gives me the same error.. :cry: 
Do you mean my target-postgres config file? Because despite the leads and activities schemas, everything else works (tasks, user,..).
Could the problem be with my metadata configuration?

**Comment by AlexanderMann** [comment]
Yeah, I mean it might be worth simplifying your schema down to _just_ the working stuff. ie, get the trouble schema _working_ even by deleting the troublesome field from the schema altogether, maybe remove the metadata, then start adding things back one by one till you get the issue again.

I am curious as to whether the problem you're having _might be_ that somehow what you're editing/making changes to isn't being picked up by `target-postgres`, like somehow the file path to your config/schema is off by a little bit, there's something cached, etc.?

**Comment by DylanDriessen** [comment]
Seems like it caches indeed, even when I only set 1 property it returns the whole schema

**Comment by AlexanderMann** [comment]
```
dylan@Dylan-linux:~/Documents/Stage/Singer$

  ~/.virtualenvs/tap-closeio/bin/tap-closeio
    --config tap-closeio/config.json
    --catalog tap-closeio/catalog_activities.json |

  ~/.virtualenvs/target-postgres/bin/target-postgres
    --config target-postgres/config.json
```

Based on your command, I'd do the following:
- check your `config.json` for `target-postgres`. I presume that's a standard config which just has a few connection things in it
- pipe the output from `tap-closeio` into a json file so that you can look at that. I am willing to bet that it's always outputting the same thing no matter what changes you make

**Comment by DylanDriessen** [comment]
[test.zip](https://github.com/datamill-co/target-postgres/files/3113523/test.zip)
It does :man_facepalming:, what do I owe?

**Comment by DylanDriessen** [comment]
Is there a way I can solve this @AlexanderMann ? I've been trying some things, but nothing seems to work out.

**Comment by AlexanderMann** [comment]
@DylanDriessen welllllllll `tap-closeio` (and most api taps) [hardcode their schemas](https://github.com/singer-io/tap-closeio/tree/master/tap_closeio/schemas). This makes development of this suppppper simple and allows for validating breaking schema changes from the source.

For _targets_, there are a couple options:
- fully support JSON Schema (for `target-postgres`, currently we don't have support for `anyOf`, `allOf`, and global/non-local `$ref`s)
- ignore/gracefully handle the bits of JSON Schema we _don't_ handle

The _better_ option is to support _as much of JSON Schema_ as possible. We have a couple issues kicking around in here which speak to that effect.

The _simpler_ option is to gracefully handle things (potentially a config/feature flag).

If you wanna discuss trying to support the missing features that'd make your life simpler here I'm happy to help however I can!

**Comment by AlexanderMann** [comment]
This issue has been open for a _while_ without any activity. @DylanDriessen did you ever get a conclusion to this?

For the record, I think this issue is most closely related to these other open issues:

#14

**Comment by DylanDriessen** [comment]
I've changed the hardcoded schema from closeio. The problem was indeed the anyOf in the schema. Thanks for all the help @AlexanderMann!
