### ISSUE TITLE
Types cannot change / mixed types

### ISSUE THREAD

**Issue by awm33** [datamill-co/target-postgres#12]
If a column type changes, the target should be able to handle that. There is no Singer standard for handling this, so we could look to Stitches standard. Though I think we can use JSON Schema to our advantage, since at least for now, we are assuming it is always available, and not handling any given JSON.

I think this comes down to:
- Identify a set of rules for handling data type changes. Try to maximize user experience, and minimize negative consequences of changing the schema.
- Implement those rules and create tests around each combination of type change cases.

**Comment by AlexanderMann** [comment]
Following the Stitch guidelines would be involved, but probably fairly rewarding. The way they handle rejected records is pretty good: https://www.stitchdata.com/docs/destinations/postgresql/#rejected-records-log

Presently we don't do type suffixes on column names (...right?). Looks like Stitch only does that on the [first detected difference](https://www.stitchdata.com/docs/data-structure/postgresql-data-loading-behavior#stitch-detects-multiple-data-types-for-a-single-colum). To that end, that'll effect the [conversation here](https://github.com/datamill-co/target-postgres/issues/18) somewhat.

I think following Stitch's example for how to handle this makes the most sense.

---------

In general I think it might make a lot of sense to start using Stitch's documentation as the specification for features added to both PostgreSQL and Redshift: https://www.stitchdata.com/docs/data-structure/postgresql-data-loading-behavior

**Comment by awm33** [comment]
@AlexanderMann The biggest reason Stitch added the rejected records was because they had no way to expose loading logs to customers at the time. We may want to consider adding a rejected logs table (I actually think it was inspired by Redshift's built-in table that is similar for COPY errors), but we could start with logging.

> Presently we don't do type suffixes on column names
No, but we could. Yes, it will effecting column naming.

**Comment by awm33** [comment]
@AlexanderMann That all sounds right, except for:
- With postgres we can just keep `string` mapped to `text` types.
- Redshift will need varchar expansion.
- For integers, do we just want to make all integers 64bit? There are table size implications there, but for practical purposes, negligible.

**Comment by AlexanderMann** [comment]
@awm33 sounds like widening is a feature to me! No sense in trying to do that yet if there's no pressing demand for it.

Once we get to Redshift, there'll be an obvious performance pr...but that's a battle for future-us.

**Comment by awm33** [comment]
@AlexanderMann Agreed. Redshift is the one with the real need for widening.

**Comment by AlexanderMann** [comment]
(sorry, accidentally pressed close!)
