### ISSUE TITLE
Large datasets cause extremely slow imports

### ISSUE THREAD

**Issue by bradleyprice** [datamill-co/target-postgres#123]
I'm currently using this target with the zendesk tap. We're using this to keep a local copy of the zendesk data, which we use to run daily reports, along with some additional use cases. I've had the import running for several days and noticed that cpu was spiking on my db instance along with some queries taking several minutes to run. After doing a bit of digging, I found that some of my tables were already into the millions of records and needed some indexes.

Specifically, the indexes needed were around the `_sdc_sequence` and `_sdc_level_{}_id` columns.

I'm wondering what the thoughts were around potentially making a PR to automatically create these indexes or if maybe it would be better to just have that noted in the documentation as to specific fields that might need to have indexes as the tables start growing.

For specifics, at the moment, these are what my largest tables (over 100k records) look like:

| table | count |
| ----- | ------ |
|tickets__custom_fields|5,418,717|
|ticket_audits__events|2,466,633|
|ticket_audits__events__value|461,196|
|tickets__tags|342,643|
|ticket_audits|234,680|
|ticket_audits__events__previous_value|118,678|

**Comment by AlexanderMann** [comment]
@bradleyprice I think we'd be extremely happy with any help on this!

The documentation is an obvious low hanging fruit, so any recommendations you have on that are very welcome.

As far as a code enhancement, do you have any specific ideas or requests for the feature?

I think we've been managing our larger installations by routinely running some `add index` commands, so it sounds like this could definitely be an improvement for everyone using this codebase. I have some ideas as to what would make the most sense, but you have more recent pain in this area and are arguably a better expert on this than I 😄

**Comment by bradleyprice** [comment]
So, I haven't had much of a chance to think about it. As soon as I have a chance I am going to gather some logs from postgres to analyze the queries being generated.

I was thinking it would be easy enough to generate an index when new schemas are being created, since we know what queries are being used to insert data into the database. The downside to this is that we could potentially be creating unused indexes, since not all tables will be large enough to need an index. Some of my tables have upwards of 10 million records, while some of them have less than 10.

I see 2 potential methods we could take:

1. Create indexes for all new tables
    * pros
      * easy
      * if a user wanted to opt-in to using the auto creation of indexes, but had previously setup indexes for their existing tables, there wouldn't be an issue
    * cons
      * potentially creating indexes that aren't needed, in the case of a small dataset
      * existing tables wouldn't get indexed (in the case of someone who is already using this target)
2. Analyze table as import happens
    * pros
      * not creating useless indexes (depending on how we decide when to create an index)
      * retroactively takes care of existing tables
    * cons
      * less efficient, since we'd have to continually check for some threshold
      * if a user had existing tables with indexes, we'd need to either check to see if an indexes exist or allow a user to configure what tables to index or not index

I assume with any method that was taking, this would need to be an "opt-in" feature, since there are probably people who would want to handle indexing themselves.

I'd love to hear more about your thoughts around potential implementations or potential issues.

Thanks!

**Comment by AlexanderMann** [comment]
Those are more or less the pros/cons I was thinking as well.

The "fun" part with the implementation is that _currently_ our logic for upserting a table breaks each operation necessary to upsert a table into a separate comand. ie, we have a `create_table`, `add_column`, `make_column_nullable`, etc. etc. Since we don't construct one large command to run on each table, we'd have to add some special logic to either:

- ensure that the columns which need indexes _exist_
- when we go to `add_column` for one of our target columns, we _also_ add index after the operation is complete

I think this _has_ to be opt-in. The simplest is definitely "add indexes for join columns" and if we run into performance problems with this for folks down the road, we can add a more complex flag which has some threshold.
