### ISSUE TITLE
JSON Schema $ref is not supported

### ISSUE THREAD

**Issue by awm33** [datamill-co/target-postgres#13]
- Add support for self referencing `$ref` (reference is within the same document).
- Identify level of effort for resolving HTTP(S) `$ref`s. Then comment and collaborate to determine if level of effort meets benefit.

**Comment by AlexanderMann** [comment]
@awm33 I think we can probably close this as we now have basic `$ref` support. When we have a feature request/run into more advanced `$ref`s usage, I think we can revisit our approach at that time.

**Comment by awm33** [comment]
Agreed
