### ISSUE TITLE
JSON Schema combinations such as "anyOf" and "allOf" are not supported

### ISSUE THREAD

**Issue by awm33** [datamill-co/target-postgres#14]
Allow for [combining schemas](https://json-schema.org/understanding-json-schema/reference/combining.html)

**Comment by AlexanderMann** [comment]
@awm33 `$allOf` seems _more_ or less straightforward. At the very least we should be able to get the _main_ use cases of it narrowed down. ie, things like `string`s with a `maxLength`, etc.

Detecting impossible types is something that might be tricky. It's not something that JSON Schema does by default on it's own, so I can see us being in a situation where we'll need to make error messages better/useful.

For `$anyOf` I think we'll need to understand widening columns or be comfortable doing early days Stitch things like making a separate column for each value based on it's `type` as well.

-------

All in all, if you wanna detail what cases you want to cover here/how you want to proceed I can start taking a stab at this.

**Comment by AlexanderMann** [comment]
## anyOf

When `anyOf` is detected, we:
- perform a column split for _each_ schema found
- persist data based on ***the first schema the provided value matches***
  1. I tell you `foo: {anyOf: [string, integer]}`, I provide you with the value `42`
  2. persist that value to `foo__i`
  3. then I provide you with `'bar'`
  4. persist that value to `foo_s`

## allOf

When `allOf` is detected we simply use the _first_ provided schema and save only that in our `simplify` JSON Schema function.

I can see users _eventually_ wanting to have the picking be smarter than just the first provided (ie, I told you `allOf : string, datetime`, use the `datetime` not the `string` as it's more specific) but I don't think doing anything clever to _start_ here is wise.

**Comment by awm33** [comment]
@AlexanderMann These could also be at the base level, eg a stream shema with:
```
{anyOf:[ {type:object,...}, {type:object,...}, {type:object,...}]}
```
In that case, we may need to only allow for root schema anyOf/allOf/oneOf to be objects. I've seen this for APIs where the schema of an endpoint can vary, like an events endpoint.

**Comment by awm33** [comment]
@AlexanderMann Me using "such as" was lazy of me. There's also "oneOf" and "not", though if "not" is difficult, I'd say not support it.

**Comment by AlexanderMann** [comment]
Guess what?!?!? Now they are 🎉 🎉 🎉
