### ISSUE TITLE
Compare Last Modified Date

### ISSUE THREAD

**Issue by tcboles** [datamill-co/target-postgres#168]
Is there a way to compare dates when inserting records to prevent older versions of a record from overwriting a new version of a record?

**Comment by awm33** [comment]
Hi @tcboles , are you seeing this happen in with records being loaded by the target?

The target already uses the `sequence` property on the Singer RECORD message. The `sequence` can be any monatomic value but is usually a timestamp. The upsert action uses the `sequence` to prevent older records from overwriting newer records. If a `sequence` isn't provided the target defaults to the current time.

**Comment by tcboles** [comment]
Hi @awm33 , Thanks for the response. I think that answers my question. I am just getting started with singer and didn't realize that is how it worked. 

Thanks again.
