### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by damianraine** [datamill-co/target-postgres#171]
I seem to be having issues install this target - other targets and taps are working fine.

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

kernal : Linux 4.15.0-1051-aws x86_64

has anyone experienced this?

Error message 
`    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-friSyy/singer-target-postgres/setup.py'"'"'; __file__='"'"'/tmp/pip-install-friSyy/singer-target-postgres/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-friSyy/singer-target-postgres/pip-egg-info
         cwd: /tmp/pip-install-friSyy/singer-target-postgres/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-friSyy/singer-target-postgres/setup.py", line 8, in <module>
        with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Comment by awm33** [comment]
Hi @damianraine , what version of python are you using?

**Comment by AlexanderMann** [comment]
^ followup on that, what's your installation process look like and what's the command you're running?

**Comment by awm33** [comment]
Hi @damianraine , if you can provide the information @AlexanderMann requested and work with us to resolve your issue, you can reopen this issue. For now, I'm closing it.
