### ISSUE TITLE
Column name normalization and error handling

### ISSUE THREAD

**Issue by awm33** [datamill-co/target-postgres#18]
Currently, target-postgres blindly uses the JSON Schema property name as the column name https://github.com/datamill-co/target-postgres/blob/master/target_postgres/postgres.py#L597

However, postgres (and redshift) have limitations on what characters can be used in column names, and the length of a column name.

The target should attempt to normalize and shorten a column, and detect conflicts with other columns after doing so, throwing an exception if a conflict us detected.

From https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS
```
SQL identifiers and key words must begin with a letter (a-z, but also letters with diacritical marks and non-Latin letters) or an underscore (_). Subsequent characters in an identifier or key word can be letters, underscores, digits (0-9), or dollar signs ($). Note that dollar signs are not allowed in identifiers according to the letter of the SQL standard, so their use might render applications less portable. The SQL standard will not define a key word that contains digits or starts or ends with an underscore, so identifiers of this form are safe against possible conflict with future extensions of the standard.

The system uses no more than NAMEDATALEN-1 bytes of an identifier; longer names can be written in commands, but they will be truncated. By default, NAMEDATALEN is 64 so the maximum identifier length is 63 bytes. If this limit is problematic, it can be raised by changing the NAMEDATALEN constant in src/include/pg_config_manual.h.
```

**Comment by AlexanderMann** [comment]
@awm33 to review how you're thinking this would proceed:
1. given a JSON Schema, translate it to SQL
2. For each column name, normalize*
3. Detect when normalized names will collide and provide details to user by referencing both the original JSON Schema values/paths, and the resulting SQL names
4. Upon pulling the SQL Schema from the target DB, alert user when a _normalized_ name will collide with what is present in the DB
  - this one is also a concern for me as we _cannot_ guarantee that the column which is present in the DB is the same as the one we have now normalized
  - to get around the above, I could see us:
    - providing some configuration options
    - if the target colunm's _type_ is the same as the one we have selected for the JSON Schema, we could potentially warn, and move on

*normalize:
- Truncate name to target DB's standards (detect either `NAMEDATALEN-1` or just hardcode for the time being)
- Shorten: ***??? (this is the part I could actually use some help with as far as what you're thinking)***

-------

If my above understanding is correct about everything I think I can easily get started on the duplicate collision in JSON Schema work. I also think that the refactoring necessary for this will result in a lot of benefits for:
- the codebase in general
- the Redshift split work
- the remaining work to "shorten" etc.

**Comment by awm33** [comment]
We could start by only removing special characters and adding an underscore if the column does not begin with a letter. Potentially also shortening to the max column name length. Failing on collisions. We'll have to deal with things in redshift like columns only differing by case.

> this one is also a concern for me as we cannot guarantee that the column which is present in the DB is the same as the one we have now normalized
Would it make sense to store the original name in a COMMENT? Then we could map it back. We could store this on the original field, or the table. Or even the original JSON Schema on the table comment. Idk if their is a length, I think a COMMENT just maps to a TEXT field in an internal table.

We should also log (info or warn) all normalizations that actually change the field name.

**Comment by AlexanderMann** [comment]
See discussion in #12. Stitch handles this by not halting the world, but rather by appending everything to an `_sdc_rejected` table in the related Schema.

**Comment by AlexanderMann** [comment]
@awm33 if the schema changes in a manner that isn't able to be handled (specifically for this discussion name length/etc.) those records end up getting dumped into the rejected table. While the _end effect_ is the same for the client, ie, "my data isn't in my table", the visibility is different, and the client actually has a way to be able to fix things etc.

**Comment by AlexanderMann** [comment]
Work that is teed up but has not _yet_ been done on this issue:

- [ ] name length issues
  - [x] detect and alert length issue
  - [ ] decide on mechanism to truncate name
  - [ ] truncate with mechanism
- [ ] table name issues (ie, you have a `stream` name which becomes the `root_table_name` or a generated `subtable_name`)
  - [x] detect table name issues
  - [ ] map invalid table name to canonicalized table name
- [ ] name _collision_ (ie, when a canonicalized/mapped/generated name collides)
  - [ ] detect and alert (_mostly done_)
  - [ ] decide on mechanism to unambiguously identify collided names
  - [ ] unambiguously identify names

**Comment by AlexanderMann** [comment]
Sooooo, fun thing:

```
target_postgres_test=# create table cats__1__adoption__immunizations__5d3f791dacf047c0ae3cebefe2af74b2 ();
NOTICE:  identifier "cats__1__adoption__immunizations__5d3f791dacf047c0ae3cebefe2af74b2" will be truncated to "cats__1__adoption__immunizations__5d3f791dacf047c0ae3cebefe2af7"
CREATE TABLE

```

That's the name of one of the temp tables we generate. That just _happens_ to work right now.

@awm33 correct me if I'm wrong, but there's literally _no_ reason for prefixing the _real_ table name onto the _temp_ table name ***OTHER THAN*** for legibility for humans...correct? ie, if I fix this (very specific) issue by just using an autogen uuid to identify the temp table, we're really not losing anything as these temp tables would be autoremoved by the transaction rollback if there were an error?

**Comment by AlexanderMann** [comment]
So that's a _harrrrddddd_ no...it's relied upon in the logic in the active version. Digging a little bit.

**Comment by AlexanderMann** [comment]
@awm33 I'd vote we close this issue out and instead create separate issues for the various things detailed in here: https://github.com/datamill-co/target-postgres/issues/18#issuecomment-443272584

**Comment by awm33** [comment]
@AlexanderMann I think that makes sense. Maybe an issue per the first level of checks/bullets in the list you created above? Can you create those then close this?

**Comment by AlexanderMann** [comment]
For reference in broken out issues:

Mechanism for normalization:
- best effort is priority
- if best effort fails and there is a collision: fail hard
- steps:
  - truncate
  - if still collision/invalid: map to `__n`
