### ISSUE TITLE
state output has duplicated lines

### ISSUE THREAD

**Issue by djdevin** [datamill-co/target-postgres#180]
When I run:

`tap-mysql -c db.json --catalog catalog.json | target-postgres -c dw.json > state.json`

It works, but the state.json looks like:

```
{"currently_syncing": null}
{"currently_syncing": "dw_corelocal-profile"}
{"currently_syncing": null, "bookmarks": {"dw_corelocal-profile": {"replication_key": "changed", "version": 1585593096034, "replication_key_value": "2020-03-27T23:32:26.000000Z"}}}
[etc...]
[etc...]
{"currently_syncing": null, "bookmarks": {etc...}
```

It looks like the state is being output over and over again, only the last line is valid. So I do a tail -n 1 state.json before I pass it back to the tap and it's fine.

**Comment by awm33** [comment]
@djdevin That is [how Singer targets output state](https://github.com/singer-io/getting-started/blob/master/docs/RUNNING_AND_DEVELOPING.md#guidelines). It's also how [target-stitch](https://github.com/singer-io/target-stitch) works.

The target only outputs state once all of the rows associated with a state message are flushed to the destination. Say this was running for an hour (or 8, any "long" period of time) and 45 minutes through the target failed (which could include whatever writes the state), this would let you pick up where you left off.

**Comment by djdevin** [comment]
Got it, I think the target I was using previously was only outputting after a successful run.
