### ISSUE TITLE
Missing pg_config causes installation failure when using pip

### ISSUE THREAD

**Issue by ns-iknox** [datamill-co/target-postgres#185]
Issue description:
Installation fails for `pip install singer-target-postgres` when installing the dependency `psycopg2` in an environment that doesn't have `pg_config` in the path.

Proposed solution:
Conditionally install the binary distribution (`psycopg2-binary`) if `pg_config` isn't found in the path.

**Comment by ns-iknox** [comment]
After some more research it's clear that regardless of installation issues, we should only be using the sdist.

From the [psycopg2 docs:](https://www.psycopg.org/docs/install.html#binary-packages)

> **Note** The `psycopg2-binary` package is meant for beginners to start playing with Python and PostgreSQL without the need to meet the build requirements.
If you are the maintainer of a published package depending on psycopg2 **you shouldn’t use `psycopg2-binary` as a module dependency**. For production use you are advised to use the source distribution.

**Comment by ns-iknox** [comment]
Closing Issue

**Comment by INGCRENGIFO** [comment]
> After some more research it's clear that regardless of installation issues, we should only be using the sdist.
> 
> From the [psycopg2 docs:](https://www.psycopg.org/docs/install.html#binary-packages)
> 
> > **Note** The `psycopg2-binary` package is meant for beginners to start playing with Python and PostgreSQL without the need to meet the build requirements.
> > If you are the maintainer of a published package depending on psycopg2 **you shouldn’t use `psycopg2-binary` as a module dependency**. For production use you are advised to use the source distribution.

Hello, how did you solve it?

**Comment by HerbiePorter** [comment]
@INGCRENGIFO You need to ensure you have the postgres client installed.  

If you're using a Mac you can use Brew: `brew install postgres`

**Comment by geofflangenderfer** [comment]
on ubuntu, `sudo apt install libpq-dev`

**Comment by vadim82** [comment]
How do we get this working on windows? I am getting this error when I try to pip install this package in windows.
```
Error: pg_config executable not found.
```
