### ISSUE TITLE
Supported Versions of :all-the-things:

### ISSUE THREAD

**Issue by AlexanderMann** [datamill-co/target-postgres#19]
# Problem
Presently we offer no guidance as to what versions of any of our dependencies we support/rely on.

The two which come to mind most readily:
- PostgreSQL
- JSON Schema

There are significant differences between each version of PSQL and each draft of JSON Schema.

## Suggestion
For JSON Schema we pick a _single_ version we support. For PSQL, I think that supporting multiple versions is reasonable and should be as simple as updating our CI to fan out over various versions of PSQL.

## Suggested Musical Pairing
https://soundcloud.com/sylvanesso/hskt

**Comment by awm33** [comment]
@AlexanderMann  Purely from a postgres perspective, I think 9.0+ is all we need to support. Perhaps even just 9.4+.

If this gains something from being able to test redshift (which was forked from 8.2 many years ago), then I could see an argument.

Based on feedback from Stitch, I think we can go with Draft 4 of JSON Schema. I added an issue in the backlog to validate incoming JSON Schema. If it doesn't match Draft 4, we can warn or throw an exception. https://github.com/datamill-co/target-postgres/issues/20
