### ISSUE TITLE
Schema error, can you guide me?

### ISSUE THREAD

**Issue by INGCRENGIFO** [datamill-co/target-postgres#192]
Hello, I am having this error making I want to synchronize data from "tap-postgres" to "target-postgres", If I do it from "tap-postgres" to "csv" it works without problem, I don't understand what may be happening.

![image](https://user-images.githubusercontent.com/12200313/93789761-e07cf180-fbf7-11ea-9d1c-0cb4cb936ca2.png)

**Comment by AlexanderMann** [comment]
@INGCRENGIFO are you all set here? Don't want to leave you in limbo if you accidentally clicked close 😄

**Comment by INGCRENGIFO** [comment]
@AlexanderMann you are very kind, I managed to find the answer on stackoverflow :)

**Comment by AkshayMAnvekar** [comment]
@INGCRENGIFO and @AlexanderMann - I'm facing a similar issue while trying to synchronize data from "tap-postgres" to "target-postgres". What is the solution to fix it?

**Comment by AlexanderMann** [comment]
@AkshayMAnvekar my _guess_ here is that that `tap-postgres` doesn't produce a valid Schema instance, and I _think_ you have to provide it with a schema of your own? @INGCRENGIFO might have some insight.

**Comment by INGCRENGIFO** [comment]
> @AkshayMAnvekar mi _conjetura_ aquí es que eso `tap-postgres`no produce una instancia de esquema válida, y _creo_ que debe proporcionarle un esquema propio. @INGCRENGIFO podría tener alguna idea.

My problem was that I had not selected the table to synchronize in the schema.
