### ISSUE TITLE
Failure on Adding a column that already exists.

### ISSUE THREAD

**Issue by kevinsanz93** [datamill-co/target-postgres#2]
When running tap-hubspot | target-redshift, during the writing of the initial batch, an error occurs caused by the trying to add a column that already exists:

````
INFO METRIC: {"type": "timer", "metric": "http_request_duration", "value": 0.6819870471954346, "tags": {"endpoint": "email", "http_status_code": 200, "status": "succeeded"}}
INFO email_events - Writing batch (35631)
ERROR Exception writing records
Traceback (most recent call last):
  File "/Users/kevinsanz/.virtualenvs/target-sql/lib/python3.6/site-packages/target_sql/target_sql.py", line 151, in write_batch
    target_table_version)
  File "/Users/kevinsanz/.virtualenvs/target-sql/lib/python3.6/site-packages/target_sql/target_sql.py", line 459, in upsert_table_schema
    schema)
  File "/Users/kevinsanz/.virtualenvs/target-sql/lib/python3.6/site-packages/target_sql/target_sql.py", line 765, in merge_put_schemas
    default_value)
  File "/Users/kevinsanz/.virtualenvs/target-sql/lib/python3.6/site-packages/target_sql/target_sql.py", line 750, in add_column
    default_value=default_value))
psycopg2.ProgrammingError: column "appid" of relation "email_events" already exists

CRITICAL column "appid" of relation "email_events" already exists

CRITICAL column "appid" of relation "email_events" already exists
````
Not sure why this is happening given that merge_put_schemas seems to account for this.

**Comment by awm33** [comment]
@kevinsanz93 Would you be able to add the current table schema in Redshift and the JSON schema it's attempting to merge in?

**Comment by awm33** [comment]
It looks like redshift always lowercases table column names.

We may want to add a field like `lowercase_columns = true/false` to the target classes to switch on postgres vs redshift.

**Comment by AlexanderMann** [comment]
For what it's worth, I _think_ this issue will be "auto-closed" once we start in on rebasing/updating/splitting the 🔴⬆️ branch to latest of master. There have been a lot of features specifically targeting issues like this.

**Comment by AlexanderMann** [comment]
@kevinsanz93 @awm33 I think this has been resolved in https://pypi.org/project/target-redshift/

**Comment by awm33** [comment]
@kevinsanz93 Closing this out. Please check out the now official `target-redshift` :)
