### ISSUE TITLE
How do I add new columns to existing table automatically?

### ISSUE THREAD

**Issue by seajhawk** [datamill-co/target-postgres#228]
I'm working with CSVs that have some date-based columns. Every few months new columns are added to the CSV. 

Is it possible to configure the datamill-co variant to add these new columns automatically?

Currently, the transferwise variant of target-postgres will add the columns new columns with the `data_flattening_max_level` config setting. 

Unfortunately, the transferwise variant has the nasty habit of ordering the columns alphabetically which makes downstream analysis difficult for those using the data because there are dozens of columns with logical groupings (name columns, demographic columns, physical address columns, mailing address columns, etc.). And, that variant doesn't seem to be getting as much attention as the datamill, so it would be great if one variant had a superset of features.

**Comment by seajhawk** [comment]
Looking through the code I found the `add_column()` function being called in `upsert_table_helper()` and so far, I can't see why that function wouldn't be called based on my config. I'm going to do some more debugging.

Oh, and I noticed the readme also mentions adding new columns, so I'm thinking this should just work.

**Comment by laurentS** [comment]
@seajhawk if I understand your problem correctly, you're using a tap to load the CSV, and pipe that into `target-postgres`. It should create the new columns automatically, if the tap produces the right schema messages. The new columns should be created at the end of the list of columns in postgres. I'm not sure why they're not added in your case.

Some random things I can think of:
- does the postgres user you use to connect from the target have permissions to modify the db schema?
- if you run the tap by itself, does it produce the `SCHEMA` and `RECORD` messages you're expecting?
- to debug, you could pipe the tap output into a file, check that it's what you expect, then pipe that file through the target. This would help make sure which side the problem is on.

**Comment by seajhawk** [comment]
@laurentS - thanks for the reply - I'm getting close!

I had tried running `meltano run tap-csv target-jsonl` and was able to see the new columns get added to the json file in /output. So I was confident that the tap was sending the new columns in the stream.

But after adding a bunch of LOGGING statements to target-postgres, I wasn't seeing any of the columns come in. It seemed that the list of columns was static for some reason even as I reordered and added new ones in different order.

Poking around under /.meltano I found that under `/.meltano/run/tap-csv` there is a properties cache file `tap-properties.json` and a `tap.properties.cache_key` file. When I deleted those files, the columns came through in the stream and were created in the database!

Now I just need to figure out how to tell meltano to ignore the cached properties.
Using the cached properties is not something I'm setting in config, but hopefully I can add a setting to tell meltano to ignore them.

(It is strange that using target-jsonl seems to tell meltano to ignore the cached properties, but using target-postgres does not...)

**Comment by laurentS** [comment]
thanks for the feedback. It sounds like it's a meltano issue, rather than something with this tap. Can I suggest you ask your question on their slack channel? They're rather responsive. And I'll let you close this issue if it's ok with you :slightly_smiling_face:

**Comment by seajhawk** [comment]
I agree about it being a Meltano issue and am closing this issue.

FYI in case someone searches for this in the future:
I found a related thread (https://meltano.slack.com/archives/C01TCRBBJD7/p1672680739956629?thread_ts=1658986134.766319&cid=C01TCRBBJD7) and am asking if there is a way configure meltano.yml to ignore the cached catalog.
