### ISSUE TITLE
Column name mapping, invalid row detection

### ISSUE THREAD

**Issue by AlexanderMann** [datamill-co/target-postgres#44]
# Motivation

In #43 we continue to expound on what the `SQLInterface` will and _will not_ do. It is quite likely that we will end up bringing column mappings under its purview as column splitting etc. is likely a shared thing in most/all RDBMS we'll want to support (🤷‍♂️). For the time being though, we fill up a `default_row` with `NULL_DEFAULT` values. If one of those fields which has been pre-filled, is not _allowed_ to be `null` in the `remote`, we will get a persistence error upon trying to load the data.

While the above is somewhat _specific_ to the mentioned pr, this same logic exists in our current implementation.

## Question

Do we want to add record validation on values after they've been serialized?

ie, do we want to perform:

https://github.com/datamill-co/target-postgres/pull/43/files#diff-5b906fece7e68cf803bb91e89b80047aR492

```py
Draft4Validator(remote_schema['schema'], ...).validate(row)
serialized_rows.append(row)
```

## Suggested Musical Pairing

https://soundcloud.com/cleacleamusic/bright-blue

**Comment by AlexanderMann** [comment]
No, this isn't someone modifying the remote. This would be something like:

- stream schema where column `a`, can't be null
- stream schema without a column `a`
- remote will blow up, even though we _know_ there needs to be an actual default value in place for `a`...

I don't think there's a really massive benefit for clients here, but I was lumping this in with "we have the information to detect this" bucket.

**Comment by AlexanderMann** [comment]
@awm33 another approach we could take here, which is more nuanced:

- detect when fields are missing which are required in the remote
- make all missing fields `nullable` (hence, no hard fail, better than making everything `null` from the start)

**Comment by awm33** [comment]
@AlexanderMann Basically, detect fields in remote that are present in remote (the database) and non-null, but are not present in the current stream schema?

I'm wondering if there are any potential consequences. The only one I can think of is if someone adds a field outside of the target. Though, couldn't we use the metadata to detect that? Since the previous version of the schema should be in the table metadata. So if column `a` is present in the current metadata, and is not present in the new schema, make the new column nullable. If it's not present, allow for it to blow up, because it may have been altered outside of the target.

**Comment by AlexanderMann** [comment]
1. Nope, we don't store that information. We only store information about columns where the colunm was mapped to another _name_
1. Actually, I think that the use case you're describing is a benefit. If I add a column to a table which is going to be appended to later AND I've made it non-nullable, when we go to stream to it later, we're going to blow up. vs, in this proposal, we'd warn you about it, but make it nullable and move on in life.

**Comment by awm33** [comment]
@AlexanderMann Oh, I thought we were storing JSON typing information in the metadata as well. Should we be?

**Comment by AlexanderMann** [comment]
@awm33 presently we're only storing that information which _cannot_ be derived from the schema itself. So for things like name `mapping`s, you can't piece that information together from the schema, so we store all of the information about that column inside the mapping. But for a stock and standard column, whose name is the exact same (casing and everything) as its originating field/property, we don't store anything.

We could store that data, but I'm not sure how much we'd get from that.

**Comment by AlexanderMann** [comment]
So while working on the table name mapping stuff, I think there is actually some benefit to be gotten by persisting all of the column information as well. I'm going to leave that alone for now as I think there's some stabilization work to be done before next Wednesday anyways.

**Comment by AlexanderMann** [comment]
This should no longer be a concern due to leveraging column paths over serialized names to pull values out etc.
