### ISSUE TITLE
Add to Pypi

### ISSUE THREAD

**Issue by awm33** [datamill-co/target-postgres#6]
[https://github.com/statsbotco/target-postgres](https://github.com/statsbotco/target-postgres) has taken the pypi project [target-postgres](https://pypi.org/project/target-postgres/) though hasn't been updated in a few months and has a blank readme. Maybe the author would be willing to give it up?

An alternative may be `singer-target-postgres`

**Comment by AlexanderMann** [comment]
@awm33 included in this issue, do you want to do continuous delivery here? ie, potentially when a `release-` branch is cut, CD just sets everything up in Pypi?

**Comment by awm33** [comment]
@AlexanderMann Maybe? It would need to know the version somehow. Typically you 1) release the version in Github (releases are git tags) 2) publish to pypi.

Also a dependency here is me setting up a datamill account/org in pypi and adding you as a collaborator.

**Comment by AlexanderMann** [comment]
So, to (2), yeah, I obvi can't help on that one 😉 

Butttttt, to (1), we can totally do that either by branch or by tag. We can setup our CI such that it _only_ executes `deploy`s (CD) on special branches/tags, and on everything else just do the CI part.

I've found in past that this makes for _much_ more consistent release processes and also means I can't mystically lose my gpg key (etc.) as it's stored in the CI provider or whatever.
