### ISSUE TITLE
Stabilize V0 of `target-postgres`

### ISSUE THREAD

**Issue by AlexanderMann** [datamill-co/target-postgres#61]
# Motivation

`Target-Postgres` has been changing dramatically for some time. While _many_ of these changes are bug fixes, or straight features, many are modifying the underlying metadata/schema and are not purely "breaking" from a "can I rebase my branch onto this" standpoint.

As such, I'm proposing a new Milestone/Issue to gather up what bugs and housekeeping we want to get in place before going under a semvar versioning guide for ***persisted metadata/schema/data ONLY***. ie, we still will not have to play nice with those who wish to write _code_ on top of our repo, but we _will_ play nice with future versions of our code and we _will_ support the data which is persisted by v0.

## Notes

Please understand that while I am in full support of making life simpler for other devs to work on top of our work, I'm much more concerned about Datamill or someone trying to use this and then getting a tonne of data moved over...which then has to be blown away because we don't know how to migrate etc.

## Outstanding Work

On the top of my mind, the work I think that needs to be done:

- [ ] in flight feature work:
  - [ ] https://github.com/datamill-co/target-postgres/issues/52
- [ ] refactor table mappings and column mappings to use similar/same structure
  - [ ] #44 
- [ ] nested support as noted in:
  - [ ] #42 
  - [ ] #58 
- [ ] Better testing
  - [ ] Full integration test against Github/BigCommerce/whatever in CI (could be low hanging fruit for bugs etc.)

## Suggested Musical Pairing

https://soundcloud.com/hotchip/huarache-lights

**Comment by AlexanderMann** [comment]
@awm33 I believe this to be done!

**Comment by awm33** [comment]
@AlexanderMann Mhmmm
