### ISSUE TITLE
Test more data cases

### ISSUE THREAD

**Issue by awm33** [datamill-co/target-postgres#7]
Test out more variations of data. Look to real world sources for examples.

**Comment by awm33** [comment]
A perfect example of why more data cases are needed:

https://github.com/datamill-co/target-postgres/issues/2

I always lowercase and snakecase my data field names, this broke on camel case on redshift. Redshift lowercases the fieldnames, postgres does not. This specific example only effects Redshift, but you can see we need more cases.

**Comment by AlexanderMann** [comment]
Example case that has not been tested:

```
{'type': 'any-sort-of-string-not-array'
 'properties': ...}
```

**Comment by awm33** [comment]
Auditing some existing tap schemas, and testing with a subset of that would give us a better idea of the breadth of cases the target will encounter.

**Comment by AlexanderMann** [comment]
PR for `defaults` in JSON Schema: https://github.com/datamill-co/target-postgres/pull/31

**Comment by AlexanderMann** [comment]
Empty strings are not possible to be replicated, and for columns which are non null strings, they cause the replication to break.

According to the [PSQL docs](https://www.postgresql.org/docs/9.0/sql-copy.html), we have a couple options:
- detect empty string, throw an intelligible error for users
- detect a control string from user input stream (even let them configure it) and use `NULL 'some-string'` in our copy command
  - if detected control string, throw intelligible error
- `FORCE_QUOTE` will force us to quote everything which is not to be interpreted as a null value. This gets around this issue _I think_ in the most straightforward/elegant manner

**Comment by AlexanderMann** [comment]
Okay, so I've got something working with `FORCE_NOT_NULL`. _Unfortunately_, what it ends up doing is making our data error even more specific:

**On columns which _are_ nullable, where you are trying to persist the empty string, `null` will be persisted instead...**

Given the above limitations, I think it might be more reasonable to detect the control `NULL`, and then Error on that. Allow users to configure the control string, and move on. It makes for much better default behaviour.

**Comment by awm33** [comment]
@AlexanderMann I think we can:

1) Set the NULL identifier in copy to "NULL" and detect nulls on the incoming data. WARN on NULL in the incoming stream (often "NULL" is meant to be NULL, so we probably don't want to error)
2) If we want a robust solution. Generate a random 128 bit string, and use that as the NULL identifier in the COPY command.

If 2 seems like it will take a lot more time than 1, we can just go with 1.

**Comment by awm33** [comment]
We've been adding more as we encounter them in the wild. Of course we should be constantly adding more test cases as we encounter more data, but this covered enough to close this issue.
