### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by awm33** [datamill-co/target-postgres#75]
The Singer standard includes metrics that are published via INFO log messages in a standard JSON format. target-postgres should publish some metrics for monitoring and diagnostic purposes.

Metrics should include:
- SQL Query timings
- Overall write_batch timings
- Batch counts
- Table persisted row counts (which may be higher than batch do to denesting)

**Comment by AlexanderMann** [comment]
To note:
    - not a lot of other targets with metrics
    - less defined things/types etc.
    - timing type
    - count type
    - tagging system
    - taps for databases will have metrics in them which are most likely the metrics we want
    - `target-redshift` might want s3 information

**Comment by AlexanderMann** [comment]
Spec from Singer on metrics: https://github.com/singer-io/getting-started/blob/4cc04f5b2dc2fa9173412c7cd84df4bf2ed0ca91/docs/SYNC_MODE.md#metric-messages

**Comment by AlexanderMann** [comment]
Code in [`singer-python`](https://github.com/singer-io/singer-python/blob/a70e03f108307ee29f02811303bc95324650f10b/singer/metrics.py)

**Comment by AlexanderMann** [comment]
Timer examples:
- https://github.com/singer-io/tap-mysql/blob/5bac530b6f5fe07194311cbb5626cc3f87be7e3b/tap_mysql/__init__.py#L639-L652

Counter examples:
- https://github.com/singer-io/tap-mysql/blob/cfd04fcf8cf60d5c679207abaa42d11af0c996be/tap_mysql/sync_strategies/common.py#L173-L175
- https://github.com/singer-io/tap-postgres/blob/3dce12abc2729fee2719d782739b0945591ec0c9/tap_postgres/sync_strategies/incremental.py#L56
- https://github.com/singer-io/tap-postgres/blob/3dce12abc2729fee2719d782739b0945591ec0c9/tap_postgres/sync_strategies/full_table.py#L41
- https://github.com/singer-io/tap-postgres/blob/3dce12abc2729fee2719d782739b0945591ec0c9/tap_postgres/sync_strategies/full_table.py#L98

**Comment by AlexanderMann** [comment]
Soooo... `tap-postgres` doesn't do anything with tags (confirmed in this repo's usage of it as well, ie CCI logs). `tap-mysql` _however_ does, but not using the "recommended" `singer-python` mechanisms:

```
    with metrics.record_counter(None) as counter:
        counter.tags['database'] = database_name
        counter.tags['table'] = catalog_entry.table
```

**Comment by awm33** [comment]
Closed by https://github.com/datamill-co/target-postgres/pull/108
